staff_manager/urls.py
from django.contrib import admin
from django.urls import path, re_path
from app01.views import depart, staff, pretty, account, task, order, index

urlpatterns = [

    path('admin/', admin.site.urls),

    # 部门管理
    path('depart/list/', depart.departList),
    path('depart/add/', depart.departAdd),
    path('depart/delete/', depart.departDelete),
    #正则表达式<int:nid>
    # http://127.0.0.1:8000/depart/1/edit/
    # http://127.0.0.1:8000/depart/3/edit/
    path('depart/<int:nid>/edit/', depart.departEdit),

    # 用户管理
    path('staff/list/', staff.staffList),
    path('staff/add/', staff.staffAdd),
    path('staff/modelform/add/', staff.staffModelFormAdd),
    path('staff/<int:nid>/edit/', staff.staffEdit),
    path('staff/<int:nid>/delete/', staff.staffDelete),

    # 靓号管理
    path('pretty/list/', pretty.prettyList),
    path('pretty/add/', pretty.prettyAdd),
    path('pretty/<int:nid>/edit/', pretty.prettyEdit),
    path('pretty/<int:nid>/delete/', pretty.prettyDelete),

    # 管理员管理
    # path('admin/list/', admin.adminList),
    # path('admin/add/', admin.adminAdd),
    # path('admin/<int:nid>/edit/', admin.adminEdit),
    # path('admin/<int:nid>/delete/', admin.adminDelete),
    # path('admin/<int:nid>/reset/', admin.adminPasswordReset),

    # 登录
    path('login/', account.login),
    path('logout/', account.logout),
    path('image/code/', account.imageCode),

    # 任务表
    path('task/list/', task.taskList),
    path('task/add/', task.taskAdd),

    # 订单表
    path('order/list/', order.orderList),
    path('order/add/', order.orderAdd),
    path('order/delete/', order.orderDelete),
    path('order/details/', order.orderDetails),
    path('order/edit/', order.orderEdit),

    # 自定义中间件的测试
    re_path('index/.*$', index.index)
]

app01/models.py
from django.db import models

# Create your models here.
class Admin(models.Model):
    """ 管理员表 """
    username = models.CharField(verbose_name='用户名', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=64)

    def __str__(self):
        return self.username

class Department(models.Model):
    """ 部门表 """
    title = models.CharField(verbose_name='标题', max_length=32)

    # 方便modelform生成时直接拿到title
    def __str__(self):
        return self.title

class Staff(models.Model):
    """ 员工表 """
    name = models.CharField(verbose_name='姓名', max_length=16)
    password = models.CharField(verbose_name='密码', max_length=64)
    age = models.IntegerField(verbose_name='年龄')
    acount = models.DecimalField(verbose_name='账户余额', max_digits=10, decimal_places=2, default=0)
    create_time = models.DateField(verbose_name="入职时间")

    # 数据库的约束
    # 创建与Department表连接的外键depart，django自动生成为depart_id
    # on_delete=models.CASCADE意味级联删除，当部门删除后，关联的员工也删除
    depart = models.ForeignKey(verbose_name='部门', to='Department', to_field='id', on_delete=models.CASCADE)

    # 删除后置空
    # depart = models.ForeignKey(to='Department', to_fields='id', on_delete=models.SET_NULL, null=True, blank=True)


    # django自带的约束
    gender_choices = (
        (1, '男'),
        (0, '女'),
    )
    gender = models.SmallIntegerField(verbose_name='性别', choices=gender_choices)

class PrettyNum(models.Model):
    """ 靓号表 """
    mobile = models.CharField(verbose_name="手机号", max_length=11)
    # 想要允许为空 null=True, blank=True
    price = models.IntegerField(verbose_name="价格", default=0)

    level_choices = (
        (1, "1级"),
        (2, "2级"),
        (3, "3级"),
        (4, "4级"),
    )
    level = models.SmallIntegerField(verbose_name="级别", choices=level_choices, default=1)

    status_choices = (
        (1, "已占用"),
        (2, "未使用")
    )
    status = models.SmallIntegerField(verbose_name="状态", choices=status_choices, default=2)

class Task(models.Model):
    """ 任务表 """
    level_choices = (
        (1, "紧急"),
        (2, "重要"),
        (3, "临时"),
    )
    level = models.SmallIntegerField(verbose_name="级别", choices=level_choices, default=1)
    title = models.CharField(verbose_name="标题", max_length=64)
    detail = models.TextField(verbose_name="详细信息")
    user = models.ForeignKey(verbose_name="负责人", to="Admin", on_delete=models.CASCADE)

class Order(models.Model):
    """ 订单表 """

    oid = models.CharField(verbose_name='订单号', max_length=64)
    title = models.CharField(verbose_name='标题', max_length=32)
    price = models.IntegerField(verbose_name='价格')

    status_choices = {
        (1, '未支付'),
        (2, '已支付'),
    }
    status = models.SmallIntegerField(verbose_name='状态', choices=status_choices, default=1)
    admin = models.ForeignKey(verbose_name='管理员', to='Admin', on_delete=models.CASCADE)

app01/views/account.py
from django.shortcuts import render, redirect, HttpResponse
from django import forms
from io import BytesIO

from app01.utils.bootstrap import BootstrapForm, BootstrapModelForm
from app01.utils.encrypt import md5
from app01.utils.code import check_code
from app01 import models

class LoginForm(BootstrapForm):
    username = forms.CharField(
        label = '用户名',
        widget = forms.TextInput,
    )
    password = forms.CharField(
        label = '密码',
        widget = forms.PasswordInput(render_value=True),
    )
    code = forms.CharField(
        label = '验证码',
        widget = forms.TextInput(),
    )
    # 钩子方法将输入框所得密码md5方便与数据库对照
    def clean_password(self):
        password_md5 = md5(self.cleaned_data['password'])
        return password_md5

def login(request):
    if request.method == 'GET':
        form  = LoginForm()
        return render(request, 'login.html',{'form':form})
    # post验证，存入数据库
    form = LoginForm(data=request.POST)
    if form.is_valid():
        #1.验证验证码是否正确
        input_code = form.cleaned_data.pop('code')
        correct_code = request.session.get('code') # 超时获得空字符串返回None
        if not correct_code:
            form.add_error('code', '验证码已超时')
            return render(request, 'login.html', {'form': form})
        if input_code.upper() != correct_code.upper():
            form.add_error('code', '验证码输入有误')
            return render(request, 'login.html', {'form': form})

        # 2.去数据库查找用户
        admin_obj = models.Admin.objects.filter(**form.cleaned_data).first()
        if not admin_obj:
            # 若没有找到用户
            form.add_error('password', '用户名或密码错误') # 为form.password追加错误
            return render(request, 'login.html', {'form': form})
        # 用户名和密码正确，写入session
        request.session['info'] = {
            'id': admin_obj.id,
            'username': admin_obj.username
        }
        # 设置用户的session时间
        request.session.set_expiry(60*60*24*7)


        return redirect('/staff/list/')
    # 数据校验失败重新输入
    return render(request, 'login.html',{'form':form})

def logout(request):
    """ 用户注销 """
    # 清除用户session并重定向
    request.session.clear()
    return redirect('/login/')

def imageCode(request):
    """ 生成图片验证码"""
    img, code_string = check_code()
    print(code_string)
    # 将正确的验证码存到session中，并设置30s有效时间
    request.session['code'] = code_string
    request.session.set_expiry(30)

    # 将验证码写如内存，并返还
    stream = BytesIO()
    img.save(stream, 'png')

    return HttpResponse(stream.getvalue())

app01/views/admin.py
from django.shortcuts import render, redirect
from django import forms
from django.core.validators import ValidationError

from app01 import models
from app01.utils.pagination import Pagination
from app01.utils.bootstrap import BootstrapModelForm
from app01.utils.encrypt import md5

def adminList(request):
    data_dict = {}
    search_data = request.GET.get('q', '')  # 获取搜索框输入数据
    # 存入信息至dict
    if search_data:
        data_dict['username__contains'] = search_data

    queryset = models.Admin.objects.filter(**data_dict).all()
    # 分页组件
    page_obj = Pagination(request, queryset)

    content = {
        'queryset': page_obj.page_queryset,
        'page_string': page_obj.html(),
        'search_data': search_data,
    }

    return  render(request, 'admin_list.html', content)

class AdminModelForm(BootstrapModelForm):
    confirm_password = forms.CharField(label='确认密码', widget=forms.PasswordInput(render_value=True))

    class Meta:
        model = models.Admin

        fields = '__all__'
        widgets = {
            'password':forms.PasswordInput(render_value=True)
        }
    # md5加密
    def clean_password(self):
        password = self.cleaned_data['password']
        return md5(password)



    # 定义钩子方法实现密码确认的验证
    def clean_confirm_password(self):

        password = self.cleaned_data.get('password')
        confirm_password = md5(self.cleaned_data['confirm_password'])
        # print(password, confirm_password)

        if password != confirm_password:
            raise ValidationError('密码不一致')

        return confirm_password


def adminAdd(request):


    if request.method == 'GET':
        form = AdminModelForm()
        return render(request, 'change.html', {'title': '添加管理员', 'form': form,})
    # post验证，存入
    form = AdminModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('/admin/list/')
    return render(request, 'change.html', {'title': '添加管理员', 'form': form,})

class AdminEditModelForm(BootstrapModelForm):
    class Meta:
        model = models.Admin
        fields = ['username']

def adminEdit(request, nid):
    row_obj = models.Admin.objects.filter(id=nid).first()
    if request.method == 'GET':
        if not row_obj:
            return redirect('/admin/list/')
        form = AdminEditModelForm(instance=row_obj)
        return render(request, 'change.html',{'form':form, 'title':'编辑管理员'})

    form = AdminEditModelForm(data=request.POST, instance=row_obj)
    if form.is_valid():
        form.save()
        return redirect('/admin/list')
    return render(request, 'change.html', {'form':form, 'title':'编辑管理员'})


def adminDelete(request, nid):
    models.Admin.objects.filter(id=nid).delete()
    return redirect('/admin/list/')


class AdminResetModelForm(BootstrapModelForm):
    confirm_password = forms.CharField(label='确认密码', widget=forms.PasswordInput(render_value=True))
    class Meta:
        model = models.Admin
        fields = ['password']
        widgets = {
            'password': forms.PasswordInput(render_value=True),
        }
    # md5加密，并实现密码不能与上次密码相同
    def clean_password(self):
        password_md5 = md5(self.cleaned_data['password'])
        exists = models.Admin.objects.filter(id=self.instance.pk, password=password_md5).exists()
        if exists:
            raise ValidationError('不能和上次密码相同')
        return password_md5

    # 定义钩子方法实现密码确认的验证
    def clean_confirm_password(self):

        password = self.cleaned_data.get('password')
        confirm_password = md5(self.cleaned_data['confirm_password'])
        # print(password, confirm_password)

        if (password) and (password != confirm_password):
            raise ValidationError('密码不一致')

        return confirm_password

def adminPasswordReset(request, nid):
    """ 管理员密码重置 """
    row_obj = models.Admin.objects.filter(id=nid).first()
    if request.method == 'GET':
        form = AdminResetModelForm()
        return render(request, 'change.html',{'title':'管理员密码重置', 'form':form})
    form = AdminResetModelForm(data=request.POST,instance=row_obj)
    if form.is_valid():
        form.save()
        return redirect('/admin/list/')
    return render(request, 'change.html',{'title':'管理员密码重置', 'form':form})

app01/views/depart.py
from django.shortcuts import render, redirect

from app01 import models
from app01.utils.pagination import Pagination


def departList(request):
    """ 部门列表 """
    # queryset = [对象， 对象， 对象]
    queryset = models.Department.objects.all()
    page_obj = Pagination(request, queryset, 2)
    content = {
        'queryset': page_obj.page_queryset,
        'page_string': page_obj.html()
    }
    return render(request, 'depart_list.html', content)

def departAdd(request):
    if request.method == 'GET':
        return render(request, 'depart_add.html')
    # 若为post，获取用户输入数据
    title = request.POST.get('title')
    # 保存到数据库
    models.Department.objects.create(title=title)
    # 重定向到list页面
    return redirect('/depart/list/')

def departDelete(request):
    """ 删除部门 """
    #get删除 127.0.0.1:8000/depart/delete/#?nid=1
    nid = request.GET.get('nid')
    # 从数据库删除
    models.Department.objects.filter(id=nid).delete()
    return redirect('/depart/list/')

def departEdit(request, nid):
    """ 编辑部门 """
    if request.method =='GET':
        row_obj = models.Department.objects.filter(id=nid).first()
        obj_title = models
        return render(request, 'depart_edit.html', {'row_obj':row_obj})
    # 若为form post的提交
    title = request.POST.get('title')
    # 根据id找到数据并update
    models.Department.objects.filter(id=nid).update(title=title)
    return redirect("/depart/list/")

app01/views/index.py
from django.shortcuts import HttpResponse


def index(request):

    return HttpResponse('成功')

app01/views/order.py
import random
from datetime import datetime

from app01 import models
from django.shortcuts import render, redirect, HttpResponse
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

from app01.utils.forms import BootstrapModelForm
from app01.utils.pagination import Pagination


class OrderModelForm(BootstrapModelForm):
    class Meta:
        model = models.Order
        exclude = ['oid', 'admin']


def orderList(request):
    form = OrderModelForm
    queryset = models.Order.objects.all().order_by('-id')
    page_obj = Pagination(request, queryset)

    content = {
        'form': form,
        'queryset': page_obj.page_queryset,
        'page_string': page_obj.html()
    }

    return render(request, 'order_list.html', content)


@csrf_exempt
def orderAdd(request):
    """ 新建订单ajax """
    form = OrderModelForm(data=request.POST)
    # 生成oid
    form.instance.oid = datetime.now().strftime('%Y%m%d%H%M%S') + str(random.randint(1000, 9999))
    # 根据session生成admin_id
    form.instance.admin_id = request.session['info'].get('id')
    if form.is_valid():
        form.save()
        return JsonResponse({'status': True})
    return JsonResponse({'status': False, 'errors': form.errors})


def orderDelete(request):
    uid = request.GET.get('uid')
    exists = models.Order.objects.filter(id=uid).exists()
    if not exists:
        return JsonResponse({'status': False, 'errors': '删除失败，该数据已经不存在！'})
    # 成功
    models.Order.objects.filter(id=uid).delete()
    return JsonResponse({'status': True})


def orderDetails(request):
    uid = request.GET.get('uid')
    exists = models.Order.objects.filter(id=uid).exists()
    if not exists:
        return JsonResponse({'status': False, 'errors': '编辑失败，该数据已经不存在！'})

    row_dict = models.Order.objects.filter(id=uid).values('title', 'price', 'status').first()

    return JsonResponse({'status': True, 'data': row_dict})

@csrf_exempt
def orderEdit(request):
    uid = request.GET.get('uid')
    exists = models.Order.objects.filter(id=uid).exists()

    if not exists:
        return JsonResponse({'status': False, 'tips': '编辑失败，该数据已经不存在！'})
    row_obj = models.Order.objects.filter(id=uid).first()
    form = OrderModelForm(data=request.POST, instance=row_obj)
    if form.is_valid():
        form.save()
        return JsonResponse({'status': True})
    return JsonResponse({'status': False, 'errors': form.errors})

app01/views/pretty.py
from django.shortcuts import render, redirect

from app01 import models
from app01.utils.forms import PrettyModelForm, PrettyEditModelForm
from app01.utils.pagination import Pagination


def prettyList(request):
    """ 靓号列表 """

    data_dict = {}
    search_data = request.GET.get('q', '')  # 获取搜索框输入数据

    # 存入信息至dict
    if search_data:
        data_dict['mobile__contains'] = search_data

    # select * from [tableName] by level desc;
    queryset = models.PrettyNum.objects.filter(**data_dict).order_by('-level')

    # 实例化分页组件
    page_obj = Pagination(request, queryset)

    context = {
        'queryset': page_obj.page_queryset,
        'page_string': page_obj.html(), #生成的HTML string
        'search_data': search_data, # 搜索框的数据
    }
    return render(request, 'pretty_list.html', context)



def prettyAdd(request):
    if request.method == 'GET':
        form = PrettyModelForm()
        return render(request, 'pretty_add.html', {'form':form})

    form = PrettyModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('/pretty/list/')
    return render(request, 'pretty_add.html', {'form': form})


def prettyEdit(request, nid):
    row_obj = models.PrettyNum.objects.filter(id=nid).first()

    if request.method == 'GET':
        form = PrettyEditModelForm(instance=row_obj)
        return render(request, 'pretty_edit.html', {'form':form})
    form = PrettyEditModelForm(data=request.POST, instance=row_obj)
    if form.is_valid():
        form.save()
        return redirect('/pretty/list/')
    return render(request, 'pretty_edit.html', {'form': form})

def prettyDelete(request, nid):
    models.PrettyNum.objects.filter(id=nid).delete()
    return redirect('/pretty/list/')

app01/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>
        .account {
            width: 400px;
            border: 1px solid #dddddd;
            border-radius: 5px;
            box-shadow: 5px 5px 20px #aaa;

            margin-left: auto;
            margin-right: auto;
            margin-top: 100px;
            padding: 20px 40px;
        }

        .account h2 {
            margin-top: 10px;
            text-align: center;
        }

        .right{
            float: right;
        }
    </style>
</head>
<body>
<div class="account">
    <h2>用户登录</h2>
    <form method="post" novalidate>
        {% csrf_token %}
        <div class="form-group">
            <label>用户名</label>
            {{ form.username }}
            <span style="color: red;">{{ form.username.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label>密码</label>
            {{ form.password }}
            <span style="color: red;">{{ form.password.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label for="id_code">图片验证码</label>
            <div class="row">
                <div class="col-xs-7">
                    {#                    <input type="text" name="code" class="form-control" placeholder="验证码">#}
                    {{ form.code }}
                    <span style="color: red;">{{ form.code.errors.0 }}</span>
                </div>
                <div class="col-xs-5">
                    <img id="image_code" src="/image/code/" style="width: 120px;">
                </div>
            </div>
        </div>
        <div class="checkbox">
            <div class="right"><a href="/forget/">忘记密码？</a></div>
        </div>
        <input type="submit" value="登 录" class="btn btn-primary">
    </form>
</div>

<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>


<script type="text/javascript">
    $(function () {
        // 页面框架加载完成之后代码自动执行
        changeCode();
    })

    function changeCode() {
        $("#image_code").click(function () {
            // 向浏览器告知src有变
            $(this)[0].src += '?';


        })
    }



</script>


</body>
</html>

app01/templates/order_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container" style="margin-bottom: 10px">
        <input type="button" class="btn btn-primary" value="新建订单1" data-toggle="modal" data-target="#myModal">
        <input type="button" class="btn btn-primary" value="新建订单2" id="btnAdd">
    </div>
    <div class="container">

        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-list" aria-hidden="true"></span>
                订单列表
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>订单号</th>
                    <th>标题</th>
                    <th>价格</th>
                    <th>状态</th>
                    <th>负责人</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <th scope="row">{{ obj.id }}</th>
                        <td>{{ obj.oid }}</td>
                        <td>{{ obj.title }}</td>
                        <td>{{ obj.price }}</td>
                        <td>{{ obj.get_status_display }}</td>
                        <td>{{ obj.admin.username }}</td>
                        <td>

                            <button uid="{{ obj.id }}" class="btn btn-primary btn-xs btn-edit">编辑</button>
                            <button uid="{{ obj.id }}" class="btn btn-danger btn-xs btn-delete
                            ">删除
                            </button>

                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <ul class="pagination">
            {{ page_string }}
        </ul>
    </div>



    <!-- 新建/编辑订单对话框 -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">添加订单</h4>
                </div>
                <div class="modal-body">
                    <form id="formAdd">

                        <div class="clearfix">
                            {% for field in form %}
                                <div class="col-xs-6">
                                    <div class="form-group" style="position: relative;margin-bottom: 20px;">
                                        <label>{{ field.label }}</label>
                                        {{ field }}
                                        <span class="error_msg" style="color: red;position: absolute;"></span>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>

                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                    <button type="button" class="btn btn-primary" id="btnSave">保存</button>
                </div>
            </div>
        </div>
    </div>

    <!-- 删除订单对话框 -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="alert alert-danger alert-dismissible fade in" role="alert">
                <h4>是否要删除该项？</h4>
                <p>点击确认后关联数据都将被删除！</p>
                <p style="text-align: right">
                    <button id="btnConfirmDelete" type="button" class="btn btn-danger">确 定</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">取 消</button>
                </p>
            </div>
        </div>
    </div>



{% endblock %}

{% block js %}
    <script type="text/javascript">
        //定义全局变量记录
        var DELETE_ID, EDIT_ID;

        $(function () {
            bindBtnAddEvent();
            bindBtnSaveEvent();
            bindBtnDeleteEvent();
            bindBtnConfirmDeleteEvent();
            bindBtnEditEvent();

        })

        function bindBtnAddEvent() {
            $('#btnAdd').click(function () {
                // 将正在编辑的ID设为空
                EDIT_ID = undefined;
                //清除错误信息
                $('.error_msg').empty();

                // 清空输入框内容
                $('#formAdd')[0].reset();
                // 点击新建按钮，显示对话框
                $('#myModalLabel').text('新建订单');

                $('#myModal').modal('show');
            })
        }

        function bindBtnSaveEvent() {
            $('#btnSave').click(function () {
                //清除错误信息
                $('.error_msg').empty();
                //向后台发请求
                if (EDIT_ID) {
                    // 编辑
                    doEdit();
                } else {
                    // 新建
                    doAdd();
                }

            })
        }

        function doAdd() {
            $.ajax({
                url: '/order/add/',
                type: 'post',
                data: $('#formAdd').serialize(),
                dataType: 'JSON',
                success: function (res) {
                    //console.log(res);
                    if (res.status) {
                        //alert('添加成功');
                        //清空表单,$('#formAdd')[0]是Dom对象
                        $('#formAdd')[0].reset();
                        //关闭对话框
                        $('#myModal').modal('hide');
                        location.reload()
                    } else {
                        //显示错误信息在对话框
                        $.each(res.errors, function (name, errorList) {
                            $('#id_' + name).next().text(errorList[0])
                        })
                    }
                }
            })
        }

        function doEdit() {
            $.ajax({
                url: '/order/edit/?uid=' + EDIT_ID,   // get传入uid

                type: 'post',
                data: $('#formAdd').serialize(),
                dataType: 'JSON',
                success: function (res) {
                    if (res.tips) {
                        alert('数据已不存在');
                    }

                    if (res.status) {
                        //清空表单,$('#formAdd')[0]是Dom对象
                        $('#formAdd')[0].reset();
                        //关闭对话框
                        $('#myModal').modal('hide');
                        location.reload()
                    } else {
                        //显示错误信息在对话框
                        $.each(res.errors, function (name, errorList) {
                            $('#id_' + name).next().text(errorList[0])
                        })
                    }
                }
            })
        }

        function bindBtnDeleteEvent() {
            $('.btn-delete').click(function () {
                //点击按钮，显示对话框
                $('#deleteModal').modal('show')
                //取到该列的id，赋值给全局变量
                DELETE_ID = $(this).attr("uid")
            })
        }

        function bindBtnConfirmDeleteEvent() {
            $('#btnConfirmDelete').click(function () {
                $.ajax({
                    url: '/order/delete',
                    type: 'get',
                    data: {
                        uid: DELETE_ID
                    },
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {
                            location.reload()
                        } else {
                            location.reload()
                            alert(res.errors)
                        }
                    }

                })
            })
        }

        function bindBtnEditEvent() {
            $('.btn-edit').click(function () {
                // 清除错误信息
                $('.error_msg').empty();

                // 获取编辑行id
                var edit_id = $(this).attr('uid');
                EDIT_ID = $(this).attr('uid');
                // ajax发送到后台
                $.ajax({
                    url: '/order/details/',
                    type: 'get',
                    data: {
                        uid: edit_id
                    },
                    dataType: 'JSON',
                    success: function (res) {
                        // console.log(res);
                        if (res.status) {
                            // 清空输入框内容
                            $('#formAdd')[0].reset();
                            // 将原有值填入输入框
                            $.each(res.data, function (title, content) {
                                $('#id_' + title).val(content);
                            })
                            // 修改弹出框标题
                            $('#myModalLabel').text('编辑订单');
                            // 弹出框
                            $('#myModal').modal('show');

                        } else {
                            alert(res.errors);
                        }
                    }
                })
            })
        }

    </script>
{% endblock %}

app01/templates/pretty_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px" >
            <a class="btn btn-success" href="/pretty/add/">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                新建靓号
            </a>
                <div style="width: 300px; float: right ">
                    <form method="get">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="搜索号码" name="q" value={{ search_data }}>
                            <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">
                                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                            </button>
                            </span>
                        </div>
                    </form>
                </div>
            </div>



        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-list" aria-hidden="true"></span>
                员工列表
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>号码</th>
                    <th>价格</th>
                    <th>等级</th>
                    <th>状态</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in queryset %}
                    <tr>
                        <th scope="row">{{ obj.id }}</th>
                        <td>{{ obj.mobile }}</td>
                        <td>{{ obj.price }}￥</td>
                        <td>{{ obj.get_level_display }}</td>
                        <td>{{ obj.get_status_display }}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="/pretty/{{ obj.id }}/edit/">编辑</a>
                            <a class="btn btn-danger btn-xs" href="/pretty/{{ obj.id }}/delete/">删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    <ul class="pagination">
        {{ page_string }}
    </ul>

    </div>
{% endblock %}